---
- name: "install webapp"
  become: yes
  hosts: prod
  tags: webapp
  tasks:
    - name: Clean Folder 
      file:
        path: "/home/{{ ansible_user }}/ansible_webapp/"
        state: absent
    - name: Create webapp directory
      file:
        path: "/home/{{ ansible_user }}/ansible_webapp/"
        state: directory
   
    - name: "git clone to folder"
      git:
        repo: https://github.com/lsniryld/static-website-example.git
        dest: /home/{{ ansible_user }}/ansible_webapp/

    - name: Generate html
      template:
        src: templates/index.html.j2
        dest: "/home/{{ ansible_user }}/ansible_webapp/index.html"
    - name: "Launching an HTTPD Container"
      docker_container:
        name: apache-server
        image: httpd
        state: started
        ports:
          - "8000:80"
        volumes:
          - /home/{{ ansible_user }}/ansible_webapp:/usr/local/apache2/htdocs/
...
